export const unitOptions = [
    { value: 'Aisle', label: 'Aisle' },
    { value: 'Bi-Monthly', label: 'Bi-Monthly' },
    { value: 'Box', label: 'Box' },
    { value: 'Bundle', label: 'Bundle' },
    { value: 'CDM', label: 'CDM' },
    { value: 'CFT', label: 'CFT' },
    { value: 'CM3', label: 'CM3' },
    { value: 'Coil KM.', label: 'Coil KM.' },
    { value: 'Core', label: 'Core' },
    { value: 'Daily', label: 'Daily' },
    { value: 'Day', label: 'Day' },
    { value: 'Dozen', label: 'Dozen' },
    { value: 'Drum', label: 'Drum' },
    { value: 'Drum-Kilometer', label: 'Drum-Kilometer' },
    { value: 'Each', label: 'Each' },
    { value: 'Feet', label: 'Feet' },
    { value: 'GB', label: 'GB' },
    { value: 'Grams', label: 'Grams' },
    { value: 'Half Yearly', label: 'Half Yearly' },
    { value: 'Hour', label: 'Hour' },
    { value: 'INR', label: 'INR' },
    { value: 'Job', label: 'Job' },
    { value: 'KBPS', label: 'KBPS' },
    { value: 'KGM', label: 'KGM' },
    { value: 'Kilometer', label: 'Kilometer' },
    { value: 'LC Gate', label: 'LC Gate' },
    { value: 'LTR', label: 'LTR' },
    { value: 'Lot', label: 'Lot' },
    { value: 'Lumpsum', label: 'Lumpsum' },
    { value: 'Lumpsump', label: 'Lumpsump' },
    { value: 'MB', label: 'MB' },
    { value: 'MNH', label: 'MNH' },
    { value: 'MT', label: 'MT' },
    { value: 'MTKM', label: 'MTKM' },
    { value: 'Man-Month', label: 'Man-Month' },
    { value: 'Man-Week', label: 'Man-Week' },
    { value: 'Mandays', label: 'Mandays' },
    { value: 'Meter', label: 'Meter' },
    { value: 'Month', label: 'Month' },
    { value: 'Monthly', label: 'Monthly' },
    { value: 'NO.', label: 'NO.' },
    { value: 'No.', label: 'No.' },
    { value: 'Node', label: 'Node' },
    { value: 'Packet', label: 'Packet' },
    { value: 'Pair', label: 'Pair' },
    { value: 'Per Block Section', label: 'Per Block Section' },
    { value: 'Per KM Per Month', label: 'Per KM Per Month' },
    { value: 'Per KM Per Quarter', label: 'Per KM Per Quarter' },
    { value: 'Per Link', label: 'Per Link' },
    { value: 'Per Location', label: 'Per Location' },
    { value: 'Per MBPS', label: 'Per MBPS' },
    { value: 'Per Meter Per Quarter', label: 'Per Meter Per Quarter' },
    { value: 'Per Sheet', label: 'Per Sheet' },
    { value: 'Per Tower Per Month', label: 'Per Tower Per Month' },
    { value: 'Per Track Circuit', label: 'Per Track Circuit' },
    { value: 'Per Unit', label: 'Per Unit' },
    { value: 'Point', label: 'Point' },
    { value: 'Pulse', label: 'Pulse' },
    { value: 'Quarterly', label: 'Quarterly' },
    { value: 'RFT', label: 'RFT' },
    { value: 'RM', label: 'RM' },
    { value: 'Rack', label: 'Rack' },
    { value: 'SFT', label: 'SFT' },
    { value: 'SMT', label: 'SMT' },
    { value: 'Sale', label: 'Sale' },
    { value: 'Second', label: 'Second' },
    { value: 'Set', label: 'Set' },
    { value: 'Site', label: 'Site' },
    { value: 'Sq.CM.', label: 'Sq.CM.' },
    { value: 'Station', label: 'Station' },
    { value: 'Sub-Lot', label: 'Sub-Lot' },
    { value: 'Sub-Lot1', label: 'Sub-Lot1' },
    { value: 'Sub-Lot2', label: 'Sub-Lot2' },
    { value: 'Sub-Lot3', label: 'Sub-Lot3' },
    { value: 'Sub-Lot4', label: 'Sub-Lot4' },
    { value: 'Sub-Lot5', label: 'Sub-Lot5' },
    { value: 'Sub-Lot6', label: 'Sub-Lot6' },
    { value: 'Sub-Lot7', label: 'Sub-Lot7' },
    { value: 'TONNE', label: 'TONNE' },
    { value: 'Ton-Kilometer', label: 'Ton-Kilometer' },
    { value: 'Unit', label: 'Unit' },
    { value: 'Weekly', label: 'Weekly' },
    { value: 'Year', label: 'Year' },
    { value: 'Yearly', label: 'Yearly' },
];